### ISSUE TITLE
Absence of twelve_bit and chroma_sample_position

### ISSUE THREAD

**Issue by VFR-maniac** [AOMediaCodec/av1-isobmff#102]
The v1.0.0 does not explicitly define the values of twelve_bit and chroma_sample_position when they are absent.
What values SHALL we set them to?

The twelvve_bit is absent if !(sh->seq_profile == 2 && cc->high_bitdepth).
The chroma_sample_position is absent if RGB format or sh->seq_profile >= 2 && subsampling_x == 0 && subsampling_y == 0.

**Comment by tomfinegan** [comment]
> The v1.0.0 does not explicitly define the values of twelve_bit and chroma_sample_position when they are absent.
> What values SHALL we set them to?

They SHALL always be equal to the values from the Sequence Header OBU.

> The twelvve_bit is absent if !(sh->seq_profile == 2 && cc->high_bitdepth).

It seems quite clear to me that twelve_bit SHALL be 0 in any case where the twelve_bit flag is absent from the Sequence Header OBU. I suppose we could make an editorial change to explicitly spell that out, but in my opinion it isn't necessary.

> The chroma_sample_position is absent if RGB format or sh->seq_profile >= 2 && subsampling_x == 0 && subsampling_y == 0.

It SHALL be 0 in this case meaning CSP_UNKNOWN[1]. Clearly not the most sensible thing when describing an RGB format, but that seems harmless. Could you explain why this is concerning-- in other words, why would an application be looking at the chroma position and subsampling values for an RGB format or for an AV1 profile for which the value is derived from the Sequence Header OBU color_config()[2]?

We could bump the box version and do something like add a chroma_fields_present flag that wraps the subsampling and position bits, but I don't think this issue is severe enough to warrant such measures.

[1] https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=131
[2] https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=44

**Comment by VFR-maniac** [comment]
>They SHALL always be equal to the values from the Sequence Header OBU.
But the values are undefined in the spec.

>It seems quite clear to me that twelve_bit SHALL be 0 in any case where the twelve_bit flag is absent from the Sequence Header OBU. I suppose we could make an editorial change to explicitly spell that out, but in my opinion it isn't necessary.

It's not clear logically it's just undefined. The av1-isobmff treats it as a field storing the value from the Sequence Header OBU and it does not define as a field which is a flag indicating 12 bit coding or not.

>It SHALL be 0 in this case meaning CSP_UNKNOWN[1]. Clearly not the most sensible thing when describing an RGB format, but that seems harmless. Could you explain why this is concerning-- in other words, why would an application be looking at the chroma position and subsampling values for an RGB format or for an AV1 profile for which the value is derived from the Sequence Header OBU color_config()[2]?

I can understand it's harmless and makes no sense but as the specification it should cover all cases we can imagine and specify a value to enable implementers to implement according to the spec blindly :)

>We could bump the box version and do something like add a chroma_fields_present flag that wraps the subsampling and position bits, but I don't think this issue is severe enough to warrant such measures.

I don't think a chroma_fields_present flag and the box version up are needed it is enough to add explicit descriptions for the absent cases since it's just undefined before and no brakes of its binary interface.
