### ISSUE TITLE
Use of colr box is not clear when color_description_present_flag is 0

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-isobmff#126]
The current spec says:
> The sample entry SHOULD contain a colr box with a colour_type set to nclx. If present, the values of colour_primaries, transfer_characteristics, and matrix_coefficients SHALL match the values given in the Sequence Header OBU (in the configOBUs field or in the associated samples) if the color_description_present_flag is set to 1. Similarly, the full_range_flag in the colr box shall match the color_range flag in the Sequence Header OBU. When configOBUs does not contain a Sequence Header OBU, this box with colour_type set to nclx SHALL be present.

It's unclear what values should be used when color_description_present_flag is 0. Should the `nclx` box declare values 2/2/2/0? Is it allowed to declare values other than 2/2/2, like 1/13/6, to override at the container-level the unknown color space from the elementary stream? That seems in line with the spirit of ISOBMFF  which says:
> If colour information is supplied in both this box, and also in the video bitstream, this box takes
precedence, and over-rides the information in the bitstream.

What about the color range? Can it be overriden?

**Comment by cconcolato** [comment]
The group discussed this issue and proposes to add a note indicating that it is fine not to have color information in the bitstream but in that case the `colr` box shall be present and should not have values 2/2/2

**Comment by wantehchang** [comment]
I found a technical complication. The color_config() part of the AV1 sequence header OBU is defined as follows:

```
color_config( ) {                                       Type
...
    color_description_present_flag                      f(1)
    if ( color_description_present_flag ) {
        color_primaries                                 f(8)
        transfer_characteristics                        f(8)
        matrix_coefficients                             f(8)
    } else {
        color_primaries = CP_UNSPECIFIED
        transfer_characteristics = TC_UNSPECIFIED
        matrix_coefficients = MC_UNSPECIFIED
    }
```

The subject of this issue is to deal with the color_description_present_flag == 0 case. One can see that the color_description_present_flag == 1 && color_primaries/transfer_characteristics/matrix_coefficients == 2/2/2 case is essentially the same as the color_description_present_flag == 0 case. Therefore, the spec probably should also address the case when color_description_present_flag is equal to 1 but color_primaries, transfer_characteristics, or matrix_coefficients is equal to 2 (unspecified).

**Comment by ValZapod** [comment]
color_description_present_flag is just for parsing bitstream... Just like VUI in HEVC has a flag that allows to specify chroma siting.

**Comment by cconcolato** [comment]
FYI https://github.com/MPEGGroup/CMAF/issues/43
