### ISSUE TITLE
On storage of Sequence Header OBUs in the sample entry

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-isobmff#136]
Currently, It is not required for a sample entry to store the Sequence Header OBU. Instead, every sync. sample is required to include a Sequence Header OBU in the sample data. This means that the decoder initialization information is always stored in stream (in-band tracks). 

I would like to understand why there is no requirement on storage of the Sequence Header OBU in the sample entry. I would always expect decoder initialization information to be present in the sample entry. This would allow:

1. to reduce the redundancy of repeating the same Sequence Header OBU in every sync sample (if it's always the same for the entire track duration)
2. initialization of the decoder without fetching the media data fragment (in case of fragmented files)
3. Sequence Header OBUs contained in the sample data would always be of higher priority (appear later in the demultiplexed bitstream as the one from the sample entry). 

Do we need to differentiate in-band and out-of-band tracks? (similar to `hev1` and `hvc1`)?

**Comment by porcelijn** [comment]
Hi Dimitry,

I think the rationale was that we _do_ want to be able to have it either way. (With sequence header OBU (only) in sample entry OR initial sequence header in sync sample.) So similar to `hvc1` and `hev1` / `avc1` and `avc3`. The main distinction with av1 spec. was that no explicit FourCCs are chosen to make this distinction; it's `av01` in both cases.

> Instead, every sync. sample is required to include a Sequence Header OBU in the sample data. This means that the decoder initialization information is always stored in stream (in-band tracks).

I do not think the spec intended to go that way. I think the intention was to say that sequence headers should go either into the `conig_obus` or be in-band, but if you choose the latter case then they should be repeated for every sync sample. 

@cconcolato Am I correct in this assertion?

While arguably, the in-band / out-of-band-agnostic design is a lofty goal, personally I think this has been a source of confusion that has lead to some weird packaging mistakes. We've seen tracks that do neither (no SQ obu in sample entry and only the first GOP starting with a Sequence Header) as well as duplicate sample entries where the only difference was that one `config_obu` also had a metadata OBU while the other did not.

We also found that instances, the `hev1` / `avc3` style exclusion of the sequence header from the sample entry greatly complicated track selection. So I would be in favour of making the sequence header mandatory or at least defining some AV1 profile that mandates the `avc1` / `hvc1`-style sample entry.

**Comment by podborski** [comment]
Thanks @porcelijn for providing interesting insights.

> I do not think the spec intended to go that way. I think the intention was to say that sequence headers should go either into the conig_obus or be in-band, but if you choose the latter case then they should be repeated for every sync sample.

Hmm, in the definition of the [Sample Format](https://aomediacodec.github.io/av1-isobmff/#sampleformat) I see:

> If an AV1 Sample is signaled as a sync sample (in the SyncSampleBox or by setting sample_is_non_sync_sample to 0), it SHALL be a Random Access Point as defined in [AV1], i.e. satisfy the following constraints:
> 
> - Its first frame is a Key Frame that has show_frame flag set to 1,
> - It contains a Sequence Header OBU before the first Frame Header OBU.

The second bullet point kind of requires you to have the Sequence Header OBU present in every sync sample, regardless of what you have stored in the sample entry, no? 

To me it also seems valuable to always have the sequence header OBU stored in the sample entry, regardless of in- or out-of-band thing.

**Comment by cconcolato** [comment]
The group discussed this issue and came to the following:
- It is believed that existing decoders (at least open source software decoders) don't need the information from the Sequence Header OBU to be initialized, because the AV1ConfigurationRecord contains already the necessary information. The SH OBU is only needed when the first frame is decoded. The group welcomes information on whether this is true for other decoders (e.g. hardware decoders).
- The AV1-ISOBMFF model is that a key frame is passed to the decoder by concatenating the contents of the configObus and the contents of the sync sample, meaning there could be duplicate SH OBUs if one was included in the configOBUs. We are not sure what the behavior would be if the 2 SH would not be identical. Probably only the latter would be used but it's not clear.

We welcome more feedback.

**Comment by porcelijn** [comment]
We rely somewhat on configOBUs. When present, we infer `colr` and resolution from `av1C`'s sequence headers in favour of other information, but our choice is arguably arbitrary. For _frame rate_ however, (required in dash MPD) we actually rely on the the SH in config OBU.

I think the rationale to exclude frame rate from `av1C` was that it should not really matter. The decoder will know what to do once it's decoding the actual media and why should there be a _constant_ frame rate at all? But that is hardly the issue when for instance you're trying to select the best media timescale or when you're building an MPD for a live stream given only the sample entry (and the first couple of media segments). There is no way to know whether putting `@min/maxFrameRate` in `<AdaptationSet>` is a realistic promise, unless framerate is intensionally signaled as part of the SampleEntry. (ie. `time_scale / (num_ticks_per_picture_minus_1 + 1)`, if timing_info_present and `equal_picture_interval`)

Again, I think this is all fine for scenario's along the lines of `avc3` / `hev1`. The group's conclusions are commensurate with that perspective.

The issue is that the spec doesn't cater very well for `avc1` / `hvc1`-like scenarios. Ie.: the sequence headers known and constant for the entire track and we _intend_ to express that property in the SampleEntry.

So reframing the subject, another solution is that given that:

>  The AV1-ISOBMFF model is that a key frame is passed to the decoder by concatenating the contents of the configObus and the contents of the sync sample

we would not need to repeat the SH in the media segment **if** it is already part of the configOBUs. But of course, that would only be valid if the requirement:

> It contains a Sequence Header OBU before the first Frame Header OBU.

were somewhat lifted / extended. What about:

> If an AV1 Sample is signaled as a sync sample (in the SyncSampleBox or by setting sample_is_non_sync_sample to 0), it SHALL be a Random Access Point as defined in [AV1], i.e. satisfy the following constraints:
> 
> - Its first frame is a Key Frame that has show_frame flag set to 1,
> - It contains a Sequence Header OBU before the first Frame Header OBU **or a Sequence Header OBU is present in the SampleEntry's `configOBUs`**

Additional constraints could address the problem of conflicting SHs, by mandating they are either in `configOBUs` or media, or that they must be identical, or that the last one always wins. (To be pedantic, this could be clarified anyway as the spec currently does not prohibit _multiple_ sequence headers in the media fragment. ;-) )

**Comment by cconcolato** [comment]
Thanks for the report.

> When present, we infer colr and resolution from av1C's sequence headers in favour of other information, but our choice is arguably arbitrary. 

Note that `colr` must be present if there is no SH in the `configOBUs`. For the resolution, why don't you use the sample entry width and height? 

> For _frame rate_ however, (required in dash MPD) we actually rely on the the SH in config OBU.

I'm sure you're aware of https://github.com/MPEGGroup/CMAF/issues/11 where the proposal is to update CMAF to recommend using the default_sample_duration value to infer frame rate. 


> The issue is that the spec doesn't cater very well for `avc1` / `hvc1`-like scenarios. Ie.: the sequence headers known and constant for the entire track and we _intend_ to express that property in the SampleEntry.

Can you clarify why, in the on-demand case, you need to put the Sequence Header in the sample entry? 

I don't think we can lift the requirement that SH has to be in each sync sample. I would rather recommend not to put the SH in the configOBUs at all.

**Comment by porcelijn** [comment]
Maybe part of the confusion lies in the intention of putting the SH in the sample entry. It's not that it's _impossible_ to infer frame rate from `mvex` or that it's _impossible_ to scan the entire stream, collecting SHs only to discover that they are all identical (although the latter has problems makes no sense in a live stream). It's that an SH in `av01`'s `configOBUs` expresses: here are the SH for this _entire_ stream.

Ie. the `avc1` analogy I'm promoting is where you've specifically configured your AV1 elementary stream encoder to use _one_ SH for the entire stream. From there, it's easy to wrap that in (f)mp4. Technically, the decoder doesn't care if the SH is given once or stripped from the sample entry and repeated redundantly for every segment. But what if you _intend_ to say: "this is how my ES is structured; we'll be using only _this_ SH throughout the whole stream"? What does it help to hide that sequence header from the SampleEntry in that case?

In a way, that is like forcing a h264 stream with fixed SPS/PPS from `avc1` into `avc3`. Forcing SHs into the media adds overhead; stripping them from the `configOBUs` makes some information cumbersome to derive. What are the benefits? Sure, `avc3` is more flexible, but what if you want to signal that you'll not be using any of that?

For clarity. I'm not arguing that AV1 should _always_ include configOBUs in the sample entry or that `avc1` is "superior" to `avc3`. But I do not understand why the spec currently embraces "the  `avc3`-flavour" of doing things even though "the `avc1` flavour" is sometimes much simpler.

Ps.: I'd also like to point out that `mvex` works for CMAF, but ISOBMFF should also work for progressive mp4.

**Comment by cconcolato** [comment]
> Maybe part of the confusion lies in the intention of putting the SH in the sample entry. [...] It's that an SH in `av01`'s `configOBUs` expresses: here are the SH for this _entire_ stream.

I'm still wondering wha the advantage of "knowing the SH for the _entire_ stream" is. Trying to summarize the arguments and my understanding. So far, you mentioned:
- It's used to get the color information. But if the SH is not present, the `colr` box has to be there, so it does not seem a valid argument.
- It's used to get the frame rate. But, depending on the encoding, the frame rate information may not be in the SH. So this is only a partial solution. In my view, the SH should not be used for that. The container should provide that information (mvex or frame rate box or else) as this is not used by the decoder (except in some edge decoder model validation cases). 
- There is overhead in repeating the SH at every KeyFrame. I agree, but that's a cost for an overall ecosystem simplfiication and harmonization of live and ondemand scenarios 

I'd like to understand a bit more what you meant by:
> We also found that instances, the hev1 / avc3 style exclusion of the sequence header from the sample entry greatly complicated track selection. 

What other information would be extracted from the SH for track selection?

In my view, there are only disadvantages in having the SH in the configOBUs:
- first, the duplication of format (ondemand/avc1 vs live/avc3) and associated complexity to be handled by all tools in the chain. 
- second, it makes it easy to create invalid content. And since anyway players will still have to cope for the cases where the promise is not kept and when the SH actually changes, it seems better to make that the default behavior.

In retrospect, we probably should not have added a `configOBUs` at all. That would have avoided cases like:
> duplicate sample entries where the only difference was that one config_obu also had a metadata OBU while the other did not.

Maybe we should clarify the case of metadata. Do you remember the example you encountered? The only metadata I can think of are: a) HDR_CLL or HDR_MDV but for both the spec recommends using the boxes versions instead, and b) for HDR10+ the spec forbids that https://aomediacodec.github.io/av1-hdr10plus/#codecconfigurationrecord.

**Comment by porcelijn** [comment]
> I'm still wondering wha the advantage of "knowing the SH for the entire stream" is. 

I'm thinking about packaging; given a bunch of mp4 tracks generate an HLS main playlist or dash MPD. You would like to be able to read the initial top level boxes and be able to fill in the blanks for representation attributes like: codec string, bitrate, language, framerate, samplerate, timescale, etc. For most codecs (aac, dolby, dts, hevc, avc1, imsc1, wvtt..) we can reliable distill this without the need to scan the entire file.

With AV1, we find that the AV1CodecConfigurationRecord bitfields (without configOBUs) are lacking for instance _frame rate_. The information usually _is_ available in "the" SH, but this SH may be in the media rather than the `configOBUs`. That is, after collecting the unique SHs preceding key frames found throughout the stream we end up with a set containing 1 element.

So, in the _frame rate_ case, where the sample entry has no `configOBUs`, we can either opt to:
- scan the entire file for SHs
- use the frame rate found in the first SH of the first segment and hope that it won't change
- use a less generic source of truth, like `mvex.default_sample_duration`
- not signal frame rate at all

I'm hoping for presence of SH in configOBUs to express a "promise from encoder to decoder" (and by extension from manifest to player) that characteristics implied by the SH are valid for all media samples. Conversely, _empty_ configOBUs would mean "no characteristics are implied" (other than the AV1CodecConfigurationRecord bitfields); the frame rate _may_ vary, for instance.

> -     first, the duplication of format (ondemand/avc1 vs live/avc3) and associated complexity to be handled by all tools in the chain.

I think we can cater for both without introducing a dedicated FourCC and all that complexity. For instance, we might require the SH is *either* in the media segments preceding the actual tiles etc. (and `configuOBUs` must be empty, like the `avc3`-case) OR the SH must be in the `configOBUs` and should not be in the media segments. Maybe designate these as "variable" vs. "fixed" sequence header profiles?

Note that since the ES decoder is always fed the `configOBUs` followed by `mdat`, the bitstream is identical (except if the SH changes throughout the stream).

> -     second, it makes it easy to create invalid content. And since anyway players will still have to cope for the cases where the promise is not kept and when the SH actually changes, it seems better to make that the default behavior.

Yes, I think a player should be able to cope with a new SH in middle of a stream, it should be lenient with it's input. But that isn't the same as saying that an encoder cannot be strict with it's output and should be able to accurately describe what that is.
For what it's worth, suppressing configOBUs does not prevent semantic inconsistencies between the in-stream SHs and the sample entry.

> In retrospect, we probably should not have added a `configOBUs` at all.

I disagree. Initially we _only_ had `configOBUs` and initial presentation delay. In retrospect I think we would have been better of if we had focussed on constraining the properties of those OBUs, rather than duplicating many, but not all of the characteristics in AV1CodecConfigurationRecord bit fields.

**Comment by cconcolato** [comment]
To try and progress this discussion, I reached out to a hardware implementor that wishes to remain anonymous. Here are their response:

1) Is it beneficial for a hardware decoder (e.g. in terms of latency) to be fed with an AV1 Sequence Header prior to receiving the first frame or does it make no real difference? 

> No latency difference.  
>
> As an aside, because of all the confusion with inline and OOB signaling as discussed in the thread, in our reference SW implementation (noting that customers and partners can also choose to write their own players so we don't control that) we have prepending OOB payloads to key frames to ensure either case is handled properly.

2) What would be the behavior of a decoder if fed 2 different consecutive Sequence Headers? Would the last one win or would it be an error?

> The second/last one would overwrite the state information and be used (no error).  This is consistent with enabling the more general behavior that occurs when sequence headers are NOT consecutive.  That is, when a "new" sequence header appears, the decoder is expected to treat the second one as the proper one moving forward.

**Comment by porcelijn** [comment]
:+1: Nice! That sounds very reasonable. So, from a (hardware) decoder perspective there is no reason to mandate either SH only in `mdat`, only in `moov` (ie. configOBUs), or in both.

If it is indeed more a matter of taste and/or what is practical given the context — then for _our_ use case I would very much like to be able to have the SHs in the init segment.

While 2. says that technically there is no decoding issue _even_ when `configOBUs` were to conflict with in-stream SHs, for our purpose we would not expect this to be the case. In a sense, such conflicts would be analogous to otherwise conflicting properties like tiles that don't match the resolution signaled in the sample entry. It might still work, but you would not want to add conflicting signalling because that beats it's purpose.

So, as a matter of packaging profile I would like to have wording along the lines of:
* `configOBUs` may be empty, in which case SHs must be present in the `mdat` and precede any sync sample *OR*
* `configOBUs` contains a SH which defines properties that are applicable to/valid for/non-conflicting with _any_ sample in the `mdat`

Reiterating: the first profile provides flexibility at the cost of modest overhead, the second profile can remove some redundancy but only if you opt-out of some flexibility upfront. Does that make sense?

**Comment by RufaelDev** [comment]
We think signalling config obus in decoderconfigrecord and no SH in the sync samples 
makes sense to enable to following use cases:

- media capabilities only based on the CMAF header (for browser based playback)
- overhead is reduced by not repeatedly including SH in samples
- information for the manifest (framerate, color spaces) can be easily retrieved from config obus in CMAF Header 
- It is easier to constrain applications, for example the current 
   version allows changing color space. It makes it clearer that 
   such are constrained/constant. 

We would recommend aom members to consider and discuss this, as similar functionality also exists in avc/hevc and feature parity could be achieved.

**Comment by cconcolato** [comment]
Thanks @porcelijn and @RufaelDev. 

Regarding your comments:
> * media capabilities only based on the CMAF header (for browser based playback)

Can you elaborate? What information is in the SH and not in the `AV1SampleEntry ` (either in the `AV1CodecConfigurationRecord` or in the some other boxes) that could be used for Media Capabilities testing?

> * overhead is reduced by not repeatedly including SH in samples

I agree but that's the cost to pay to reduce overall system complexity. It's a tradeoff. The cost seems rather low. I just checked some encodes, the size of the SH is 13 bytes. If you assume short 2s segments, that's 52 bits/sec. I'm sure we can find scenarios where the overhead would be higher but I don't think it would go very high.

> * information for the manifest (framerate, color spaces) can be easily retrieved from config obus in CMAF Header

There are 2 parts here: 
- color spaces. It can be retrieved by the codec-agnostic `colr` box. It is mandated when SH is not present. Additionally if SH is present and the `colr` box is present, the box overrides the bitstream per ISOBMFF, so it makes sense to rely on the box. I would also argue that parsing the `colr` is much easier than parsing the SH.
- framerate. We could mandate the setting of `default_sample_duration`. Also, one could infer the frame rate from the level, as levels describe the upper bound of width * height * frame rate. If a device supports a level, it should support the max frame rate for that level, given a resolution.

> * It is easier to constrain applications, for example the current
>   version allows changing color space. It makes it clearer that
>   such are constrained/constant.

I don't follow this comment.

> We would recommend aom members to consider and discuss this, as similar functionality also exists in avc/hevc and feature parity could be achieved.

The group discussed this issue. At this stage, the group does not feel that changing the specification is necessary, except maybe for a note explaining the context. The group welcomes further feedback. Parity in complexity (i.e. handing 2 4CCs) with AVC/HEVC is not desired.

As an additional data point, the AVIF specification explicitly recommends not using the SH in the configOBUs. Creating video streams with such configuration can ease the extraction of KeyFrames into AVIF images.

My understanding at this stage is that if you had a clear way to get the frame rate, you would not need the SH at all in the `configOBUs`, correct?

**Comment by cconcolato** [comment]
> For another, what about progressive mp4?

Can you elaborate on that? In progressive mp4 all timing information is given in the moov. So, you can determine the frame rate.

**Comment by porcelijn** [comment]
Fair enough. So, the strategy is something like:

-  for CMAF check if `mvex` signals default duration and use that. Older fmp4 profiles, may do the same, assume variable framerate otherwise. 
- for progressive, scan all the samples and use good judgement. Beware of 10MHz or 90kHz timescales and drop frames, caveat for the last sample and stay away from older ffmpeg versions that (mis)used the first sample to reflect ctos/edit lists.

I would much more like to have a simple, reliable O(1) way of determining how the encoder was configured. The encoder _can_ express exactly how it's configured in a container-agnostic manner through a SH. The MP4 container _includes_ a mechanism to pass this SH, in the `configOBUs`.
So I don't understand what would be the benefits of prohibiting the use of the mechanism. What makes AV1 so different from other codecs that in this case it's best to assume that a sample is a frame and rely on the container to infer what the encoder is doing? Would not you agree that various interpretations of (f)mp4 versions, profiles make this indirect derivation more opaque rather simple and robust?

**Comment by cconcolato** [comment]
I think your description of the strategy is also what I would do.

I agree that for the progressive case it's not that simple, but it's not so difficult either.

One benefit of this strategy is that it's codec-agnostic. Relying on SH would be codec-specific. Also, I don't think using SH is simpler (parsing the SH is hard) or more robust (not all encodes would set the timing_info_present flag).

**Comment by porcelijn** [comment]
> One benefit of this strategy is that it's codec-agnostic. Relying on SH would be codec-specific.

I like player agnostic, but ISOBMFF in general doesn't provide this. So the container based strategy would work only when we can safely assume (future) CMAF profile is applicable or hope other inference is good enough. This being an AV1-ISOBMFF binding, I think we ought to do better.

> Also, I don't think using SH is simpler (parsing the SH is hard) or more robust (not all encodes would set the timing_info_present flag).

Yes, it's not trivial, but any decoder should (by definition) be able to it anyway.

Weary of comparing pears to apples, I had a quick look at how the [WebM](https://github.com/ietf-wg-cellar/matroska-specification/blob/master/codec/av1.md) project thinks about this topic and found this:

> This structure MAY be followed by OBUs that are valid for the whole CVS.

I think that captures my take: it's optional and only makes sense if it's applicable to each segment.
To your `timing_info_present` argument, they seem to made the same mistake unfortunately, though:

> The [timing_info_present_flag] of the Sequence Header OBU SHOULD be 0. Even when it is 1 the presentation time of the Frame Header OBUs in Blocks should be discarded. In other words, only the timestamps given by the Matroska container MUST be used. 

I believe they meant to say (okay, I admit that I'm biased :smiley:) "don't trust timestamps in the elementary stream" — I totally agree they should not be there. But that's a different use than using `timing_info_present_flag = 1` to signal that `equal_picture_interval = 1` and `time_scale / (num_ticks_per_picture_minus_1 + 1)` = frame rate. So, then `timing_info_present_flag` may be false, but it shouldn't unless framerate is variable or unknown.

**Comment by cconcolato** [comment]
Given the updates in the MPEG side about signaling of frame rate for fragmented files using `trex` `default_sample_duration` (and possibly flags) (also related to #159), we think this issue can be closed without action.
