### ISSUE TITLE
Remove the constraint on CleanApertureBox 'clap' from section 2.3.4

### ISSUE THREAD

**Issue by peterhliu** [AOMediaCodec/av1-isobmff#149]
The spec states that "The CleanApertureBox clap SHOULD not be present". This is intended for CMAF instead of ISOBMFF. For generic MP4 file container, this optional field can be present. Section 2 is for ISOBMFF. So the constraint should be removed.

**Comment by cconcolato** [comment]
I would agree. I don't recall exactly why the restrictions was put in that section and not in the CMAF section (or left out because implied by CMAF).

**Comment by cconcolato** [comment]
The group discussed this issue and agrees that the sentence should probably be removed, especially since the AV1 video spec does not have in-stream cropping options like some other codecs. We want to make sure however to leave opportunities for people to comment in case there was a valid reason to put this restriction in the first place.

**Comment by podborski** [comment]
Agree to remove.
