### ISSUE TITLE
Questions about "obu_has_size_field set to 1 except for the last OBU in the sample"

### ISSUE THREAD

**Issue by rbouqueau** [AOMediaCodec/av1-isobmff#26]
Hi,

As a maintainer of GPAC I wanted to express my opinion about this optimization.

This was done in AVC and HEVC and was a major source of bugs.

It breaks the concept of separation of layers by forcing the muxer to rewrite the bitstream and also by forcing the bitstream reader to get the sample size from the muxer (to retrieve the omitted size information).

Additionally it adds complexity or makes assumptions:
 1. When importing the content (parsing) we "may" need modify the bitstream.
 2. If I am a player, the muxer copies me the sample, ```obu_has_size_field``` is 0, and I can't parse this OBU type. What happens?
 2. When exporting the raw streams from an MP4 we "may" need to modify the bitstream.
 3. When re-importing content extracted from another MP4 muxer with the ```obu_has_size_field``` not set to 1 again, the content is not muxable again unless we can parse the full last OBU of each frame.
 4. Other operations that may make requirements on this field that I may have forgotten.

The optimization is around 1 byte per sample. At 30 fps it translates to 8 * 30 = 240 bit per second.

What's your opinion about this tradeoff?

cc @jeanlf

**Comment by tomfinegan** [comment]
> It breaks the concept of separation of layers by forcing the muxer to rewrite the bitstream and also by forcing the bitstream reader to get the sample size from the muxer (to retrieve the omitted size information).

It forces nothing on the muxer. It is an optional optimization. The spec text is:

> except for the last OBU in the sample, for which obu_has_size_field MAY be set to 0, 

A muxer is free to leave the bitstream alone.

> When importing the content (parsing) we "may" need modify the bitstream.

Why would a parser have to do anything? Whether the size field is present or not the parser can hand the bytes from a sample off for processing elsewhere. It need not touch the data contained within the sample. 

Maybe I'm missing something: Why would a parser need to modify the bitstream? The OBUs remain valid in both situations, the only difference is how the length is determined by parsers that aren't AV1 decoders (the length field versus inference based on length of the sample).

> When exporting the raw streams from an MP4 we "may" need to modify the bitstream.

Toggling a bit and coding an unsigned LEB128 integer does not seem that onerous a burden.

> When re-importing content extracted from another MP4 muxer with the obu_has_size_field not set to 1 again, the content is not muxable again unless we can parse the full last OBU of each frame.

Why can't the muxer repackage the Temporal Unit as-is?

> The optimization is around 1 byte per sample. At 30 fps it translates to 8 * 30 = 240 bit per second.

> What's your opinion about this tradeoff?

My opinion is that it's an optional optimization that's potentially useful for extreme low data rate use cases. A muxer is free to never implement this behavior.

**Comment by rbouqueau** [comment]
> A muxer is free to never implement this behavior.

Correct. That's why I opened this issue: I was tempted to implement it to spare the byte but I thought about how the other tools may be impacted. 

Let's take an example. Some decoders (NVDec, Android MediaCodec, ...) are not fed with samples (e.g. AV1 TUs) but with bitstreams. If the demuxer sends TUs as-is to such a decoder and that one last OBU has no size field and cannot be parsed entirely by the decoder, how will the decoder find the next OBU?

**Comment by tomfinegan** [comment]
> Let's take an example. Some decoders (NVDec, Android MediaCodec, ...) are not fed with samples (e.g. AV1 TUs) but with bitstreams. If the demuxer sends TUs as-is to such a decoder and that one last OBU has no size field and cannot be parsed entirely by the decoder, how will the decoder find the next OBU?

You are describing a non-conformant decoder.

**Comment by tomfinegan** [comment]
>  You are describing a non-conformant decoder.

To be fair, I don't think libaom supports this situation yet. 

Is the issue here that it's optional to do this, and that muxers/parsers have to look? I would be OK with adding additional text stating explicitly that parsers must undo the optimization when outputting AV1 TUs into decoding pipelines. I'm not comfortable removing the option of the optimization because it adds some complexity.

AV1 ISOBMFF is already requiring that muxers have in depth knowledge of parts of AV1. Take AV1ForwardKeyFrameSampleGroupEntry as an example: muxers will need to parse OBU Frame/FrameHeader's to determine the correct value of fwd_distance. In comparison to the size field situation, fwd_distance and properly writing AV1ForwardKeyFrameSampleGroupEntry seems much more complicated.

**Comment by tomfinegan** [comment]
> The optimization is around 1 byte per sample. At 30 fps it translates to 8 * 30 = 240 bit per second.

One additional point: I disagree that it's a 1 byte per sample optimization. It's closer to 2. At 30 kbits/second you're already crossing the threshold for 1 byte OBU lengths in an AV1 bitstream:

127 * 30 * 8 = 30480 bits/sec

At 50 kbits/sec many, if not most, of those OBUs will have 2 byte size fields as any OBU with a payload length greater than 127 bytes will be coded to 2 bytes (or more).

**Comment by cconcolato** [comment]
> You are describing a non-conformant decoder.

Actually, that's a good question: is a Section-5 bitstream that has some `obu_has_size_field` set to 0 invalid? I couldn't find any statement regarding that in the spec. I interpret that as: conformant decoders should be able to handle it. I think that's a problem. Maybe, the base video spec should be fixed to mandate that when Annex B is not used, `obu_has_size_field` shall be set to be 1 (at least for OBUs that cannot be parsed without the size).
That said, I agree that AV1 ISOBMFF spec should have a note indicating that: 
> When extracting OBUs from an ISOBMFF file, and depending on the capabilities of the decoder processing these OBUs, ISOBMFF parsers may need to either set the `obu_has_size_field` to 1 for some OBUs if not already set, or use the length-delimited bitstream format.

Also, you indicate:
 > AV1 ISOBMFF is already requiring that muxers have in depth knowledge of parts of AV1.

This is not correct. The only requirements to be able to import an AV1 bitstream are to be able to identify:
- max width/height (and changes of these values)
- TU boundaries, 
- and KF with show_frame=1. 

All other features (e.g. sample groups) are optional. Writers don't have to generate them. Readers can ignore them.

**Comment by rbouqueau** [comment]
>>When extracting OBUs from an ISOBMFF file, and depending on the capabilities of the decoder processing these OBUs, ISOBMFF parsers may need to either set the obu_has_size_field to 1 for some OBUs if not already set, or use the length-delimited bitstream format.
>
>I think this would be a good addition.

Ok.

Could we signal at the ISOBMFF level that OBU with missing sizes may be present? (e.g. a compatible brand for low latency av1).

The FFmpeg demuxer will likely copy the entire segment. For AVC/HEVC FFmpeg had a bitstream filter from the ISOBMFF canonical format to Annex B ; ther projects using FFmpeg (VLC, browsers, etc.) also have their own converters or heuristics. To mitigate possible issues:
 - Do we know if the other formats (TS, RTP, ...) also support this missing size optimization?
 - If not, do we have a way to ensure the last OBU is always entirely parsable by a decoder?

**Comment by tomfinegan** [comment]
> Could we signal at the ISOBMFF level that OBU with missing sizes may be present? (e.g. a compatible brand for low latency av1).

I think it's safer to require that compliant parsers handle both modes. As the spec currently is written it's clear that to be compliant a parser must handle omitted size fields.

> Do we know if the other formats (TS, RTP, ...) also support this missing size optimization?

No, they have not yet been specified.

> If not, do we have a way to ensure the last OBU is always entirely parsable by a decoder?

No, and this cannot be guaranteed. AV1 supports private metadata OBUs. Decoders that do not understand a private metadata OBU must skip the OBU. This is one reason why the size must always be present in the low overhead bitstream format[1]-- a private metadata OBU in the middle of a temporal unit could break a decoder without a size field. You can only guarantee that an OBU will be consumed (or ignored). It's not possible to guarantee that it will always be "decoded" (where in this case decoded means parsed/read/etc).  

> This adds a lot of complexity in demuxers for a gain that is not obvious to me

Using existing YT VP9 144p 30 fps encodes as an example. These streams are currently encoded at 95 kilobits. For the sake of this discussion let's assume AV1 uses the same rate. For this format half of a percent of the entire video bitrate would be consumed by size fields that can be omitted from the container. AV1 streams will likely use a lower bitrate than VP9, and the percentage of bits spent on the size fields will be higher.

> ISOBMFF encapsulation at such rates is much higher than what you are trying to gain.

I understand that the ISOBMFF encapsulation will add quite a bit of additional overhead on its own. I don't think that's a good reason to drop an optimization that reduces the overhead of the bitstream itself.

[1] http://av1-spec.argondesign.com/av1-spec/av1-spec.html#low-overhead-bitstream-format

**Comment by tomfinegan** [comment]
Closing this as the discussion seems to have run it's course. We can reopen if needed.

**Comment by cconcolato** [comment]
Adding more context to this discussion:

From side discussions, the issue seems to be related to how Android deals with video streams coming from ISOBMFF files. IIUC, Android does not consume "frames" but byte streams. When encrypted, you have to pass a parseable byte stream (with all size fields) and the sample auxiliary information. This means you would have to reintroduce the missing size field and update the encryption auxiliary information (byte offsets). 

Is that correct? Could we have more input from Android experts?

**Comment by cconcolato** [comment]
Regarding the proposal in #48, it feels awkward to have a different payload in clear vs encrypted bitstreams. It means that encryption tools will have to modify the input before encrypting ... 

Regarding the processing of decrypting a stream that has missing TD or size fields, I can see two cases:
a) the interface to the decoder is sample-by-sample. There is no need to add OBU TD nor the final length field. Demuxed data is decrypted as is and passed to the decoder.
b) the interface to the decoder requires a raw bitstream with TD and last size. These need to be added. The question is when/where? The API between the Demuxer and the Decryptor cannot be just a byte stream, because you also have to communicate the Sample Auxiliary Information. So one could imagine that in the process of building that data for the Decryptor, OBU TD and size fields are added and SAI adjusted. If this is too complex, one could also imagine that when reconstructing a raw bitstream after decryption, the TD and size field could be added. The complexity does not look tremendous.

The compromise here is between A) accept #48 and have encrypted bitstreams larger than clear ones and with a different payload (and muxer/encryptor tools slightly more complex) vs. B) keep the current situation making the player slightly more complex (but having a simpler encryption process). 

I favor B for consistency in the bitstream. I propose that we close this issue without merging #48, maybe modifying the note that we added in #29 to say:

> NOTE: When extracting OBUs from an ISOBMFF file, and depending on the capabilities of the decoder processing these OBUs, ISOBMFF parsers MAY need to either:
> - set the [=obu_has_size_field=] to 1 for some OBUs if not already set, add the associated size field, add Temporal Delimiter OBUs, 
> - or use the length-delimited bitstream format as defined in Annex B of [=AV1=].
>
> If encryption is used, similar operations MAY have to be done before or after decryption depending on the demuxer/decryptor/decoder architecture."

**Comment by cconcolato** [comment]
Closed with #56
