### ISSUE TITLE
Fullbox version vs version field

### ISSUE THREAD

**Issue by tdaede** [AOMediaCodec/av1-isobmff#71]
Do we care about the fullbox version field at all? Currently it doesn't match our "version" field. That's OK, just wanted to check.

**Comment by cconcolato** [comment]
Initially, the box was made a FullBox to match the VP9 vpcC and to have a version field, and also because typically in ISOBMFF, boxes that have fields are versioned. Now that the record has its own version field, I don't see a reason for av1C to be a FullBox. We could turn that FullBox into a Box (like avcC or hvcC). If not, we should make them match.

**Comment by jamrial** [comment]
Turning the fullbox into a box sounds like the best option, since it saves four bytes. And either that or bumping the fullbox version to 1 will both ensure that files muxed following the spec before the recent changes will be rejected by demuxers compliant with the final revision of the spec. Similarly, files created by complaint muxers will be rejected by old demuxers.

This is also be a good chance to rename AV1CodecConfigurationRecordv1 back to AV1CodecConfigurationRecord. No way to misparse anything after the above change, and the "v1" suffix is kinda ugly.
