### ISSUE TITLE
Single Sequence Header OBU

### ISSUE THREAD

**Issue by robUx4** [AOMediaCodec/av1-isobmff#75]
Following #46 #50 and before I update the Matroska mapping, I'd like some clarifications:

- should the SH OBU be the first in `configOBUs` ? If it's ever to be used, that would make parsers easier.
- If there are more than one which one is the valid one ? Given they're supposed to be prepended to the raw bitstream I assume the last one will apply. So that means a parser would still need to look through all the OBUs to find the right one (it's also possible people could have fun and put it after 10000 metadata OBU and it's still valid)
- is this SH OBU any useful at all in the configuration box ? I'm thinking of dropping it entirely from Matroska (which would be compatible with the ISOBMFF mapping) since the SH OBU is still meant to be present in the bitstream where there's a RAP (see #67)
- are the metadata OBU useful as well ? In Matroska it's possible to signal the HDR in different parts, is it possible in a more standard way in ISOBMFF ? Also with dynamic metadata it's not even meaningful apart from saying there's a kind of HDR in the file.

**Comment by jamrial** [comment]
> should the SH OBU be the first in configOBUs ? If it's ever to be used, that would make parsers easier.

Demuxer/Parsers shouldn't need to read the SH OBU anymore now that all the fields they mainly care about are part of av1C. Only decoders should care about it for every other value in it.
Enforcing ordering can come in handy i guess if a demuxer still wants to parse the SH, so i wouldn't be against it.

> If there are more than one which one is the valid one ? Given they're supposed to be prepended to the raw bitstream I assume the last one will apply.

Taking into account https://bugs.chromium.org/p/aomedia/issues/detail?id=2012, i think the first one. In any case, this spec states at most one SH OBU is expected in av1C.

> is this SH OBU any useful at all in the configuration box ? I'm thinking of dropping it entirely from Matroska (which would be compatible with the ISOBMFF mapping) since the SH OBU is still meant to be present in the bitstream where there's a RAP (see #67)

ConfigOBUs are meant to be used to assemble the bitstream at every RAP (even if it was decided that the SH can't be omitted in sample data), and decoders can still use them for initialization before any sample data is available. Being global headers, they are meant to be in the Codec Configuration Box. libaom even has an API meant to fetch them (aforementioned libaom issue).
I imagine most demuxers also don't bother to parse the optional sps in h264/hevc in either avcc/hvcc or mkv codecprivate, since the information they mainly care about is already available at the container level.

Global OBU presence, especially being optional, is the ideal scenario as proven by other codecs. Lets not change things for no gain.

> are the metadata OBU useful as well ? In Matroska it's possible to signal the HDR in different parts, is it possible in a more standard way in ISOBMFF ? Also with dynamic metadata it's not even meaningful apart from saying there's a kind of HDR in the file.

As much as SEI in hevc, i guess. It is also global metadata. New types can always be defined in the future as well.
And yes, this spec adopted the isobmff's mdcv and clli boxes for HDR medatada.

**Comment by cconcolato** [comment]
> should the SH OBU be the first in configOBUs ? If it's ever to be used, that would make parsers easier.

Could be changed, yes.

> If there are more than one which one is the valid one ?

Good point. I think we should make it stricter than the current note, saying that it SHALL be at most one.

> Given they're supposed to be prepended to the raw bitstream I assume the last one will apply.

They're not supposed to be prepended. They can be. I agree for the case of the SH, given that it has to be present in the RAP samples, you only need it if you want to initialize decoders in advance, more than with the fields in the config record, but not sure when this is needed.

> Taking into account https://bugs.chromium.org/p/aomedia/issues/detail?id=2012, i think the first one. In any case, this spec states at most one SH OBU is expected in av1C.

The AV1 spec says they have to be identical (except for operating point info), so it should not matter, unless we are talking about processing of invalid, non-conformant files.

> So that means a parser would still need to look through all the OBUs to find the right one (it's also possible people could have fun and put it after 10000 metadata OBU and it's still valid)

Pathological case ... but your concern would be addressed with the fact that it is first.

> is this SH OBU any useful at all in the configuration box ?

Maybe not anymore.

> are the metadata OBU useful as well ?

As indicated for HDR, we recommend using boxes instead of OBU. However, you never know what metadata people can come up with ... 

As summary, I would suggest:
- Clarify (more than in a note) that at most one SH may be present in the configOBUs
- Mandate that if present, it is the first OBU
Agree?

**Comment by jamrial** [comment]
>As summary, I would suggest:
> 
>- Clarify (more than in a note) that at most one SH may be present in the configOBUs
>- Mandate that if present, it is the first OBU
> 
>Agree?

Sounds good to me.

**Comment by tomfinegan** [comment]
>> As summary, I would suggest:

>> Clarify (more than in a note) that at most one SH may be present in the configOBUs
>> Mandate that if present, it is the first OBU
>> Agree?

> Sounds good to me.

Agreed.

**Comment by robUx4** [comment]
> Pathological case ... but your concern would be addressed with the fact that it is first.

My idea comes from IETF rules where there has to be a security section explaining how the spec can be abused and what should be done to avoid it. I think it's a good principle in general or avoiding designs that can lead to abuse in the first place.

**Comment by robUx4** [comment]
> I agree for the case of the SH, given that it has to be present in the RAP samples, you only need it if you want to initialize decoders in advance, more than with the fields in the config record, but not sure when this is needed.

I think that would be the main use case: init the codec before any of the bitstream is loaded. Unlike PPS/SPS the structure we created is foreign to a codec and would likely not be enough for the codec to work with. But a real SH OBU it would understand. So in light of this I added it back to Matroska as well as the metadata in case some others than HDR are ever added.

We now have fully compatible extra data.
