### ISSUE TITLE
Tile Subsamples

### ISSUE THREAD

**Issue by tinskip** [AOMediaCodec/av1-isobmff#81]
Why the requirement for each time to be in its own subsample?  Also, the diagrams do not reflect any kind of subsample delimitation in the red "TG Tiles" box.

**Comment by cconcolato** [comment]
In simple cases, when there is one tile per tile group, this does not change what we had before: the entire payload is encrypted. 
The only changes are when you actually have multiple tiles. In this case, when doing pattern encryption, this ensures that each tile has encrypted data. It was deemed that the cost of having multiple subsamples per tile group would be acceptable because one would only use tiles with higher resolutions, and the overhead would be small. But it's true there would be an overhead increase for tiled low bitrates but tiling already introduces overhead. 

I agree the diagrams would need to be updated.

**Comment by kqyang** [comment]
@cconcolato I don't see the benefit of having one subsample per tile in https://github.com/AOMediaCodec/av1-isobmff/issues/81#issuecomment-413988740 nor in https://aomediacodec.github.io/av1-isobmff/.

Does it improve decryption and decoding efficiency? If so, what is it? 

If there are only downsides with no gain or minimal gain, it should be dropped.

**Comment by cconcolato** [comment]
> @cconcolato I don't see the benefit of having one subsample per tile in #81 (comment) nor in https://aomediacodec.github.io/av1-isobmff/.

As indicated above:
> this ensures that each tile has encrypted data

More precisely, if you have just one subsample per tile group, it is possible with 'cbcs' and its pattern mode that some tiles would not start with encrypted bytes (possibly enabling partial decoding) and that some tiles would fall between the encrypted bytes (arguably in low bitrates or small tiles). I received feedback that it was a problem for some people.

> Does it improve decryption and decoding efficiency? If so, what is it?

I had also feedback that some use cases involving mixing/remuxing of tiles would not be possible if the entire tile group would be in a single subsample.

> If there are only downsides with no gain or minimal gain, it should be dropped.

For the typical configuration, 1 tile per frame and thus 1 tile group, there is no downside because it does not change compared to 1-subsample-per-tile-group case. 
For configurations using multiple tiles, the alternative would be to place one tile per tile group but this incurs some overhead. Also, using multiple subsamples does not increase decryption complexity, or only slightly.

**Comment by kqyang** [comment]
Thanks for the quick reply. I missed `this ensures that each tile has encrypted data` in https://github.com/AOMediaCodec/av1-isobmff/issues/81#issuecomment-413988740.

I think it will be helpful to include the reasons in the spec.

**Comment by cconcolato** [comment]
@tinskip are you satisfied with the answers here?

**Comment by tinskip** [comment]
In that case I believe you ought to modify the diagram or add a new one to reflect this.  Seems important as it would allow parallel processing of encrypted tiles.

**Comment by tomfinegan** [comment]
@tinskip The time necessary to create new diagrams before the end of the week has not materialized, so we'll be dropping the diagrams entirely. See:
https://github.com/AOMediaCodec/av1-isobmff/pull/91
