### ISSUE TITLE
AV1MetadataSampleGroupEntry for multiple Metadata OBUs in samples

### ISSUE THREAD

**Issue by VFR-maniac** [AOMediaCodec/av1-isobmff#83]
Relationship between sbgp and sgpd for a particular grouping type is 1:1 not 1:N. So I wonder how to indicate all metadata types inside samples by AV1MetadataSampleGroupEntry when samples contain two or more types of Metadata OBUs.

````
class AV1MetadataSampleGroupEntry extends VisualSampleGroupEntry('av1M') {
  unsigned int (16) metadata_type;
}
````

Currently, only one metadata_type can be indicated per sample unless I misread something.

**Comment by cconcolato** [comment]
Thank for the review. I'm not sure what the use cases are for multiple metadata types per sample, but you're right we probably should allow it. 

I can see different ways to do it:
1. keep the current sample group definition and define a new one for multiple types, in this version or a future version of the spec

2. introduce a loop in the current entry
```
class AV1MetadataSampleGroupEntry extends VisualSampleGroupEntry('av1M') {
  unsigned int (8) metadata_count;
  for (i = 1 ; i <= entry_count ; i++){
     unsigned int (16) metadata_type;
  }
}
```
I'd expect most the time the count to be 1 though. If you want to signal multiple types of metadata you will have to introduce multiple configurations of samples through multiple `sgpd` entries. So searching for a given type of metadata will involve first finding all entries in `sgpd` that contain the given type and then finding in the `sbgp` all samples that refer to those entries. Also adding indication for a new metadata type means adding a new entry for the new configuration and changing the `group_description_index` for those samples.

3. or empty the current sample group entry 
```
class AV1MetadataSampleGroupEntry extends VisualSampleGroupEntry('av1M') {
  }
```
and define the `grouping_type_parameter` to be
```
{ 
   unsigned int (16) reserved = 0;
   unsigned int (16) metadata_type;
}
```
In this case, the `sgpd` would only contain one entry of type `av1M` no matter how many metadata types are signaled but the `sbgp` could contain multiple `av1M`, each with the appropriate `grouping_type_parameter` indicating the metadata type, but in typical case probably only 1. Searching for a particular metadata type means scanning only the sbgp boxes in the track or track fragment and matching the `grouping type parameter`. 

I have a technical preference for option 3. 

Note that given that we have entered the final review period of this version of the spec, if we go for option 2 or 3, it will have to be formally approved by the Codec Working Group at the same time as the Release Candidate version, otherwise for option 1 we can wait until after approval of v1.

**Comment by tomfinegan** [comment]
> I have a technical preference for option 3.

Same here, but let's see what @VFR-maniac has to add in reply to your follow up.

**Comment by VFR-maniac** [comment]
LGTM about option 3 :)

BTW, I realized that sbgp : sgpd = N : 1 for a particular grouping_type. I thought it's 1:1 since the spec of ISOBMFF says
```
Box Type: ‘sgpd’
Container: Sample Table Box (‘stbl’) or Track Fragment Box (‘traf’)
Mandatory: No
Quantity: Zero or more, with one for each Sample to Group Box.
```

I think the description of `Quantity` is wrong. It should be the following.
```
Quantity: Zero or more, with one for each grouping
type of Sample to Group Box.
```

**Comment by cconcolato** [comment]
> I think the description of Quantity is wrong.

Yes. This is being fixed in a coming new edition of ISOBMFF.

**Comment by cconcolato** [comment]
Received feedback that it might be good to use the reserved 16 bits to be able to distinguish between multiple metadata obu of the same metadata_type, e.g. ITU-T T.35. Will address in additional commit to the PR.

**Comment by alexismt73** [comment]
In the PR it seems you are using the first 16 bytes of the metadata_itut_t35 structure. This would mean that you would be capturing the 8 MSBs of the itu_t_t35_terminal_provider_code (defined as u(16)), which might not contain any useful information for most applications. Would it be better to instead define the reserved 16 bits as to contain the country code and the 8 LSBs of the terminal provider code. That is, maybe use the following text instead: 
"In this version of the specification, metadata_specific_parameters is only defined when metadata_type is set to METADATA_TYPE_ITUT_T35. When metadata_type is equal to METADATA_TYPE_ITUT_T35, the value metadata_specific_parameters SHALL be set equal to (itu_t_t35_country_code << 8) | (itu_t_t35_terminal_provider_code & 0xFF), which can be found in the metadata_itut_t35 structure."

**Comment by cconcolato** [comment]
@alexismt73 there was a typo. It's not 16 bytes but 16 bits. Fixed in https://github.com/AOMediaCodec/av1-isobmff/commit/e1d97628e2faf02466773a73544ab75270fed787

**Comment by cconcolato** [comment]
@alexismt73 Regarding your proposed text:
- what should we do with the country code extension byte, ignore it? See also below.
- can one actually use the itu_t_t35_terminal_provider_code without itu_t_t35_terminal_provider_oriented_code?

In the light of the change above, given that 16 bits for the metadata_type seems large, I'm wondering if we shouldn't define it to be 8bits, leaving 24 bits for the specific_parameters, in which case we could decide to take:
- the first 3 bytes of the payload as is, 
- or the country code + extension + LSB of terminal_provider_code, 
- or country code + full terminal_provider_code, 
- or country code + LSB of terminal_provider_code + LSB of itu_t_t35_terminal_provider_oriented_code.

Regarding the country code extension byte, I find confusing documentation:
- Some specs define it simply as 8 bits: https://www.etsi.org/deliver/etsi_ts/103500_103599/103572/01.01.01_60/ts_103572v010101p.pdf (2018-03) says:
```
user_data_registered_itu_t_t35 () { 
    itu_t_t35_country_code b(8)
    itu_t_t35_terminal_provider_code u(16)
    itu_t_t35_terminal_provider_oriented_code f(32)
    data_type_code u(8)
    ST2094-10_data ()
    reserved_ff_8bits u(8)
} 
```
Some other documents like https://www.sra.samsung.com/assets/User-data-registered-itu-t-t35-SEI-message-for-ST-2094-40-v1.1.pdf use the same syntax as above.

While AVC/H.264 (2017-04 edition) potentially define it with an extra 8-bit field:
``` 
user_data_registered_itu_t_t35( payloadSize ) {
   itu_t_t35_country_code b(8)
   if( itu_t_t35_country_code != 0xFF )
      i = 1
   else {
      itu_t_t35_country_code_extension_byte b(8)
      i = 2
   }
   do {
      itu_t_t35_payload_byte b(8)
      i++
   } while( i < payloadSize )
}
```
HEVC has the same syntax as AVC, and defines an extension byte for the country code.
Is there a problem here?

**Comment by alexismt73** [comment]
I did not notice the byte bug earlier. Good that was fixed.

With regards to the extension, I intentionally skipped it. I would doubt you would have applications that would include multiple such metadata with different values (I would expect the use of this is rare). See here which seems to suggest that no such case has been defined yet. 

https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.35-200002-I!!PDF-E&type=items

By explicitly specifying the terminal provider code in this element we can basically ignore the extension country code. But since not used (apparently), you can also modify this to use the second byte in the payload of t.35, in which case we would not have to parse the country code (thus simpler). I am ok with either solution.

**Comment by cconcolato** [comment]
@alexismt73 Does https://github.com/AOMediaCodec/av1-isobmff/pull/86/commits/e43b54d1da8454eff0cdacb89c6782262d563972 work for you?
