### ISSUE TITLE
Pattern encryption with pattern 1:9 or 1:0?

### ISSUE THREAD

**Issue by kqyang** [AOMediaCodec/av1-isobmff#87]
> When the protected scheme <code>[=cbcs=]</code> is used, samples SHALL be protected using subsample encryption and SHALL use pattern encryption. In particular, pattern encryption with <code>crypt_byte_block</code> = 1 and <code>skip_byte_block</code> = 0 SHALL be supported.

Should it be skip_byte_block = 9 instead of = 0?

**Comment by cconcolato** [comment]
No. 

Given that 1:9 is recommended by CENC, it should already be supported. 

1:0 means 100% encryption. Given that it is not so clear in CENC that this should be supported, we emphasized in the AV1 spec.

**Comment by kqyang** [comment]
> Given that 1:9 is recommended by CENC, it should already be supported.

That is recommended, but it is not equivalent to "required".

This spec emphasis that pattern 1:0 shall be supported, so you are requiring 1:0 to be supported and leaving recommended setting 1:9 to be optional. 

What is the rational of requiring 1:0, or 100% encryption to be supported for "cbcs"?

This pattern defeats the purpose of pattern encryption and violates multiple clauses in CENC spec.

> 10.4 ‘cbcs’ AES-CBC subsample pattern encryption scheme
> ...
> Encrypted video tracks using NAL Structured Video conforming to ISO/IEC 14496-15 SHALL be
protected using Subsample encryption specified in 9.5, and SHALL use pattern encryption as specified
in 9.6. As a result, the fields crypt_byte_block and skip_byte_block SHALL NOT be 0.

This section is for NAL structured video but I think it should also apply to other video codecs, including AV1 for consistency.

And also this clause, 1+0 != 10.

> Pattern Block length, i.e. crypt_byte_block + skip_byte_block SHOULD equal 10.

**Comment by cconcolato** [comment]
> This spec emphasis that pattern 1:0 shall be supported, so you are requiring 1:0 to be supported and leaving recommended setting 1:9 to be optional.

This text was written with the thinking that it would be obvious from the CENC spec that 1:9 was already supported (per last sentence you quoted). And the current AV1-ISOBMFF text says:
> SHALL use pattern encryption. In particular, pattern encryption with crypt_byte_block = 1 and skip_byte_block = 0 SHALL be supported.

Note the use of "in particular", which is meant to say everything that is required or recommended in CENC is still required or recommended.

> What is the rational of requiring 1:0, or 100% encryption to be supported for "cbcs"?

In practice, it was reported that it is already supported by various implementations. However, some people think wrongly that it is not conformant to the CENC spec. The sentence is meant to remove that ambiguity. Also, given that `cbc1` is not required nor spec'd, it is safe to make it clear that a 100% encryption using CBC is still possible.

> This pattern defeats the purpose of pattern encryption 

In many applications, the trade-off between decryption complexity and security level is such that a 10% encryption or 90% encryption are OK. In some it may not. This leaves the door open to 100% encryption, if people want to use it. But this requires awareness by decryptors.

> and violates multiple clauses in CENC spec.

I disagree.

> This section is for NAL structured video but I think it should also apply to other video codecs, including AV1 for consistency.

As you wrote, it applies to NAL structured videos. For AV1, we have the liberty to say how it applies. This does not violate the spec. Because 100% cbcs encryption is supported, making it clear does support consistency. 

> And also this clause, 1+0 != 10.
> 
> Pattern Block length, i.e. crypt_byte_block + skip_byte_block SHOULD equal 10.

Note that it's a 'SHOULD' not a 'SHALL'.

I'm open to suggestion on how to rephrase the text to make it clear that all combinations of crypt/skip values are possible including 1:9 and 1:0 (or 10:0 if you prefer as that would be matching the last sentence you quoted).

**Comment by kqyang** [comment]
I'd prefer supporting cbc1 if you want 100% encryption, which was designed for that purpose. It is misleading and causes confusions if you allow "exceptions" for av1 when using CENC (even if the exception is explicitly spelled out).

**Comment by cconcolato** [comment]
I have rephrased the text based on your input in pull request https://github.com/AOMediaCodec/av1-isobmff/pull/92.

**Comment by cconcolato** [comment]
closed per #92
